[package]
name = "generate-random-vectors"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
hnsw_redux = { version = "0.1.0", path = "../hnsw_redux" }
