[workspace]
resolver = "2"
members = [
  "hnsw-redux"
, "index-vectors", "knn", "normalize", "search-collation", "test-recall", "time-load"]

[profile.release]
debug = true

[profile.assert]
inherits = "release"
debug-assertions = true
overflow-checks = true
