[workspace]
resolver = "2"
members = [
  "hnsw-redux"
, "index-vectors", "normalize", "test-recall"]

[profile.release]
debug = true

[profile.assert]
inherits = "release"
debug-assertions = true
overflow-checks = true
