[package]
name = "search-collation"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.18", features = ["derive"] }
csv = "1.3.0"
os = "0.1.0"
serde_json = "1.0.128"
